version: 2
updates:
  - package-ecosystem: npm
    directory: "/"

    # update dependencies on sunday at 9:00AM CST
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
<<<<<<< HEAD
      timezone: "America/Chicago"
=======
      timezone: "america/chicago"
>>>>>>> cf7ae82954cc7d45af62cbfef25c6f3e9533841b

    # keep all dependencies up-to-date
    allow:
      - dependency-type: "all"

    # check this setting, might need to assign to mergify-bot
    # else assign to self so you get notified.
    assignees:
      - "SpencerDuball"

    # see how this plays with mergify, don't need to update the
    # package and trigger release with only a dev-deps update
    commit-message:
      prefix: "update(deps)"
      prefix-development: "update(dev-deps)"
      include: "scope"

    labels:
      - "npm"
      - "dependencies"
