version: 2
updates:
  - package-ecosystem: npm
    directory: "/"

    # update dependencies on sunday at 9:00AM CST
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "America/Chicago"

    # keep all dependencies up-to-date
    allow:
      - dependency-type: "all"

    # see how this plays with mergify, don't need to update the
    # package and trigger release with only a dev-deps update
    commit-message:
      prefix: "bump"
      prefix-development: "bump"
      include: "scope"

    labels:
      - "dependency"
