pull_request_rules:
  - name: Automatic merge for dependency updates
    conditions:
      - author=dependabot[bot]
      - check-success=Test
    actions:
      merge:
        method: merge
  - name: Automatic merge when reviewed
    conditions:
      - check-success=Test
      - "approved-reviews-by=SpencerDuball"
    actions:
      merge:
        method: merge
