pull_request_rules:
  - name: Automatic merge for dependency updates
    conditions:
      - check-success=Test
      - check-success=Lint Pull Request
      - author=dependabot[bot]
    actions:
      merge:
        method: merge
  - name: Automatic merge when reviewed
    conditions:
      - check-success=Test
      - check-success=Lint Pull Request
      - approved-reviews-by=SpencerDuball
    actions:
      merge:
        method: merge
