name: Lint Pull Request
on:
  pull_request_target:
    types:
      - fix
      - feat
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
