name: Release
on:
  push:
    branches: [main]

jobs:
  # PUBLISH_TO_NPM: ✅
  # publish-to-npm job exists to publish a new patch or minor version to NPM.
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
